#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Make Menuconfig

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt.git
  REPO_BRANCH: openwrt-23.05
  CONFIG_FILE: diff.config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Load custom feeds
      run: |
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Add mosdns
      id: mosdns
      run: |
       cd openwrt
       mkdir -p package/passwall/mosdns
       cd package/passwall/mosdns
       git init
       git remote add origin https://github.com/sbwml/luci-app-mosdns.git
       git config core.sparsecheckout true
       echo "luci-app-mosdns" >> .git/info/sparse-checkout
       echo "mosdns" >> .git/info/sparse-checkout
       echo "v2dat" >> .git/info/sparse-checkout
       git pull --depth 1 origin v5
       git branch --set-upstream-to=origin/v5 master
       
    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: SSH connection to Actions
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false

    - name: Make diffconfig
      run: cd openwrt && ./scripts/diffconfig.sh > diff.config
  
    - name: Upload config
      uses: actions/upload-artifact@main
      with:
        name: config
        path: openwrt/diff.config

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.REPO_TOKEN }}
        repository: ${{ github.repository }}
        delete_workflow_pattern: Make Menuconfig
        retain_days: 0
        keep_minimum_runs: 1
