#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# 连接到网页ssh终端后（开始） Ctrl + C 健
# cd openwrt
# make menuconfig
# 配置好后退终端输入  exit

name: Make Menuconfig

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-23.05
  CONFIG_FILE: .diffconfig
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part4.sh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Load custom feeds
      run: |
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: delete package
      id: delete
      run: |
        cd openwrt
        git clone -b main https://github.com/fw876/helloworld package/passwall
        sudo rm -rf package/passwall/mosdns
        git clone -b dev https://github.com/douglarek/luci-app-homeproxy.git package/passwall/luci-app-homeproxy
        git clone -b main https://github.com/xiaorouji/openwrt-passwall.git package/passwall/p
        mv package/passwall/p/luci-app-passwall package/passwall/luci-app-passwall
        sudo rm -rf package/passwall/p/
        git clone -b main https://github.com/xiaorouji/openwrt-passwall2.git package/passwall/a
        mv package/passwall/a/luci-app-passwall2 package/passwall/luci-app-passwall2
        sudo rm -rf package/passwall/a/
    
    - name: Add brook
      id: passwall_brook
      run: |
       cd openwrt
       mkdir -p package/passwall/brook
       cd package/passwall/brook
       git init
       git remote add origin https://github.com/xiaorouji/openwrt-passwall-packages.git
       git config core.sparsecheckout true
       echo "brook" >> .git/info/sparse-checkout
       git pull --depth 1 origin main
       git branch --set-upstream-to=origin/main master
       
    - name: Add pdnsd-alt
      id: passwall_pdnsd-alt
      run: |
       cd openwrt
       mkdir -p package/passwall/pdnsd-alt
       cd package/passwall/pdnsd-alt
       git init
       git remote add origin https://github.com/xiaorouji/openwrt-passwall-packages.git
       git config core.sparsecheckout true
       echo "pdnsd-alt" >> .git/info/sparse-checkout
       git pull --depth 1 origin main
       git branch --set-upstream-to=origin/main master

    - name: Add sing-box
      id: passwall_sing-box
      run: |
       cd openwrt
       mkdir -p package/passwall/sing-box
       cd package/passwall/sing-box
       git init
       git remote add origin https://github.com/xiaorouji/openwrt-passwall-packages.git
       git config core.sparsecheckout true
       echo "sing-box" >> .git/info/sparse-checkout
       git pull --depth 1 origin main
       git branch --set-upstream-to=origin/main master
       
    - name: Add ssocks
      id: passwall_ssocks
      run: |
       cd openwrt
       mkdir -p package/passwall/ssocks
       cd package/passwall/ssocks
       git init
       git remote add origin https://github.com/xiaorouji/openwrt-passwall-packages.git
       git config core.sparsecheckout true
       echo "ssocks" >> .git/info/sparse-checkout
       git pull --depth 1 origin main
       git branch --set-upstream-to=origin/main master
       
    - name: Add trojan-go
      id: passwall_trojan-go
      run: |
       cd openwrt
       mkdir -p package/passwall/trojan-go
       cd package/passwall/trojan-go
       git init
       git remote add origin https://github.com/xiaorouji/openwrt-passwall-packages.git
       git config core.sparsecheckout true
       echo "trojan-go" >> .git/info/sparse-checkout
       git pull --depth 1 origin main
       git branch --set-upstream-to=origin/main master

    - name: Add trojan-plus
      id: passwall_trojan-plus
      run: |
       cd openwrt
       mkdir -p package/passwall/trojan-plus
       cd package/passwall/trojan-plus
       git init
       git remote add origin https://github.com/xiaorouji/openwrt-passwall-packages.git
       git config core.sparsecheckout true
       echo "trojan-plus" >> .git/info/sparse-checkout
       git pull --depth 1 origin main
       git branch --set-upstream-to=origin/main master
    
    - name: Add openclash
      id: openclash
      run: |
       cd openwrt
       mkdir -p package/passwall/openclash
       cd package/passwall/openclash
       git init
       git remote add origin https://github.com/vernesong/OpenClash.git
       git config core.sparsecheckout true
       echo "luci-app-openclash" >> .git/info/sparse-checkout
       git pull --depth 1 origin master
       git branch --set-upstream-to=origin/master master

    - name: Add mosdns
      id: mosdns
      run: |
       cd openwrt
       mkdir -p package/passwall/mosdns
       cd package/passwall/mosdns
       git init
       git remote add origin https://github.com/sbwml/luci-app-mosdns.git
       git config core.sparsecheckout true
       echo "luci-app-mosdns" >> .git/info/sparse-checkout
       echo "mosdns" >> .git/info/sparse-checkout
       echo "v2dat" >> .git/info/sparse-checkout
       git pull --depth 1 origin v5
       git branch --set-upstream-to=origin/v5 master

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: SSH connection to Actions
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false

    - name: Make diffconfig
      run: cd openwrt && ./scripts/diffconfig.sh > diff.config
  
    - name: Upload config
      uses: actions/upload-artifact@main
      with:
        name: config
        path: openwrt/diff.config

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 1
